### ISSUE TITLE
AssemblyContexts von CompositeComponents

### ISSUE THREAD

**Issue by uwecl** [uwecl/MDSD-Praktikum#14]
Im Moment aggregiert eine `CompositeComponent` mindestens zwei `AssemblyContexts`. So ist es im Model Editor jedoch nicht möglich einer `CompositeComponent` bestehende `AssemblyContexts` aus dem Assembly-View-Type-Modell zuzuweisen. Lediglich provided und required `Interfaces` können hinzugefügt werden (über die Vererbung von `Component`). 

Heißt das, dass die Verbindung zwischen `CompositeComponent` und `AssemblyContext` eine einfache Assoziation sein muss?

**Comment by uebaa** [comment]
> Note that assembly contexts that are not a direct
> part of a system but reside within a composite component cannot be allocated on containers.
> They are implicitly allocated within the allocation contexts that implement their
> hosting composite component.

Anhand dieser Sätze würd ich sagen dass die von der `CompositeCompent` aggregierten `Assembly Contexts` nicht aus dem `AssemblyContext` des Systems referenziert (also bestehende) werden sondern vom `CompositeComponent` "mit gebracht" werden.

Meiner Meinung nach würde man im Repository-View-Type-Modell dem `CompositeComponent mediaStore` drei `AssemblyContexts` zuweisen die jeweils die entsprechenden `Components` instanziieren und dem `AssemblyContexts` des Systems nur der `AssemblyContext` der `CompositeComponent` bekannt ist und das ist so in der aktuellen Version des Meta-Modells möglich.

Was meint ihr dazu?

**Comment by uwecl** [comment]
Ja, da hast du wahrscheinlich recht. Klingt zumindest nachvollziehbar. Dem System ist natürlich aber auch noch der `AssemblyContext` der `WebGUI` bekannt. ;)

Werde ich morgen so in dem MediaFilesSystem-Modell anpassen.
