### ISSUE TITLE
Missing services and delegation connector at system?

### ISSUE THREAD

**Issue by uebaa** [uwecl/MDSD-Praktikum#19]
> If a component provides an interface it provides services corresponding to the signatures of
> the provided interface.
> 
> Provided and required interfaces of a component result in provided and required
> roles for the assembly contexts of the component

Fehlt bei dem AssemblyContext des Systems vielleicht noch 2 `Services` und 1 `DelegationConnector`? Und zwar Services die die Signaturen `HTTPDownload` und `HTTPUpload` realisieren. Der `DelegationConnector` hätte dann die Rolle `ProvidedRole` und das Source Interface `HTTP`. 

Das ähnelt dann ziemlich dem CompositeComponent doch wenn das System auch als Komponente gesehen wird, dann müsste dies noch mit modelliert werden.

Was meint ihr?

**Comment by uwecl** [comment]
Mich stört da so bisschen der Teil "[...] AssemblyContext des Systems [...]". Ein `AssemblyContext` instanziiert eine Komponente. Gäbe es demnach einen `AssemblyContext` des Systems, würde das doch bedeuten, dass das System an sich als Komponente betrachtet werden würde. Zudem frage ich mich dann, wo dieser `AssemblyContext` "verwaltet" wird. Im System selbst?

Meinem Verständnis nach hat ein System lediglich Schnittstellen und kapselt die existierenden `AssemblyContexts`:

> A system also encapsulates assembly contexts and provides at least one interface.

(_@uebaa, du beziehst dich schon auf das Metamodell und nicht auf die Modellierung des Beispiels, oder?_)

**Comment by uebaa** [comment]
Oh ja `AssemblyContext` war falsch ausgedrückt, ich meinte den Assembly-View-Type. 

Also ich bin drauf gestoßen als ich mir die Modellierung des Beispiels angeschaut habe und das Gefühl hatte dass bei `assembly.componentbasedsystem` die erwähnten Sachen fehlen.

**Comment by uwecl** [comment]
Okay, du hast recht, beim System an sich fehlen noch die Schnittstellen. Die werden meiner Meinung nach aber nicht als `Services` modelliert. Zumindest gibt unser Modell das gar nicht her. Ich denke das geht aber auch mit dem Text so in Ordnung. Eben genau deshalb:

> A system also encapsulates assembly contexts and provides at least one interface.

Sie sollten aber denke ich auch nicht als `Interfaces` eingebunden werden (wie es derzeit modelliert ist), weil sonst keine Unterscheidung zwischen _provided_ und _required_ gemacht werden kann. D.h. man müsste, wenn man nach dem Text geht, dem `ComponentBasedSystem` eine oder mehrere `Roles` zuweisen. Das wäre in der Tat jedoch dann das Gleiche wie bei einer `Component`. Was dafür sprechen würde, dass man sagt, ein System wird als `Component` bzw. genauer gesagt als `CompositeComponent`repräsentiert.

Kennt ein `ComponentBasedSystem` also eine `CompositeComponent` ohne `BehaviourDescription`, welche das System _repräsentiert_?

**Comment by uwecl** [comment]
@daseit kannst du dir das bitte noch anschauen?
