### ISSUE TITLE
Xtext Grammatik erstellen

### ISSUE THREAD

**Issue by uwecl** [uwecl/MDSD-Praktikum#22]
Xtext Grammatik muss erstellt werden.

Diese kann direkt aus dem Metamodell generiert werden. Da gibt es derzeit aber noch einige Fehlermeldungen (siehe entsprechende Mail von Dominik).

**Comment by uwecl** [comment]
Ich habe versucht die Grammatik mit den Hinweisen von Dominik zu erstellen. Dies funktioniert allerdings momentan nur in soweit, dass der Import keine Fehler mehr aufwirft. Beim Ausführen des Workflows allerdings, können die ecore Dateien / Pakete nicht gefunden werden:

```
821  [main] ERROR xt.generator.XtextGeneratorLanguage  - Error loading 'componentBasedSystem.ecore'
1100 [main] ERROR xt.generator.XtextGeneratorLanguage  - [XtextLinkingDiagnostic: null:6 Couldn't resolve reference to EPackage 'platform:/resource/ComponentBasedSystem/model/componentBasedSystem.ecore'., XtextLinkingDiagnostic: null:8 Couldn't resolve reference to EPackage 'platform:/resource/ComponentBasedSystem/model/componentBasedSystem.ecore#//dataTypes'., XtextLinkingDiagnostic: null:9 Couldn't resolve reference to EPackage 'platform:/resource/ComponentBasedSystem/model/componentBasedSystem.ecore#//roles'., XtextLinkingDiagnostic: null:10 Couldn't resolve reference to EPackage
...
```

**Comment by uwecl** [comment]
Der oben beschriebene Fehler kommt jedoch nur dann zustande, wenn im Workflow der Pfad zum Genmodel **absolut** angegeben wird (`referencedResource = "/Users/.../ComponentBasedSystem/model/ComponentBasedSystem.genmodel"`).

Gebe ich den Pfad dort, wie auch bei den Imports in der `.xtext`-Datei, als Platform-URI an (`referencedResource = "platform:/resource/ComponentBasedSystem/model/ComponentBasedSystem.genmodel"`), dann kann der Workflow erst gar nicht ausgeführt werden:  

```
689  [main] ERROR mf.mwe2.launch.runtime.Mwe2Launcher  - Problems running workflow edu.kit.ipd.sdq.mdsdpc.mydsl.GenerateMyDsl: java.io.IOException: The path '/ComponentBasedSystem/model/ComponentBasedSystem.genmodel' is unmapped
```

**Comment by uwecl** [comment]
Fehler konnte (vorerst) behoben werden. Mehr dazu auf der [Wiki-Seite](https://github.com/uwecl/MDSD-Praktikum/wiki/Xtext#anpassen-des-workflows).

Es muss noch geprüft werden, ob der Editor auch korrekt funktioniert.

**Comment by uwecl** [comment]
So, die aktuell lauffähige Version liegt jetzt im _xtext_-Branch: [https://github.com/uwecl/MDSD-Praktikum/commits/xtext](https://github.com/uwecl/MDSD-Praktikum/commits/xtext)

**Comment by uwecl** [comment]
Das ist mittlerweile abgeschlossen, oder @uebaa?

**Comment by uebaa** [comment]
bis auf eine Sache: Die Validation eines OCL-Constraints verursacht einen Fehler. Darum werde ich mich aber noch kümmern

**Comment by uwecl** [comment]
Kann das jetzt geschlossen werden, @uebaa?
