### ISSUE TITLE
Referenz von ComponenBasedSystem zu Allocation hinzufügen

### ISSUE THREAD

**Issue by daseit** [uwecl/MDSD-Praktikum#23]
Für Constraint `AssemblyContextConsistent` notwendig, um auf die `AllocationContexts`zugreifen zu können.

**Comment by uwecl** [comment]
Im Metamodell wurde die Referenz bereits hinzugefügt. Hat sich das Issue damit dann erledigt, @daseit? Oder fehlt das Constraint noch?
