### ISSUE TITLE
Metamodell überarbeiten

### ISSUE THREAD

**Issue by uwecl** [uwecl/MDSD-Praktikum#3]
Metamodell auf Vollständigkeit prüfen und hinsichtlich Qualität verbessern.

**Comment by daseit** [comment]
Role braucht noch einen Namen, oder?

**Comment by daseit** [comment]
Was aggregiert denn die Assembly Connectors? EnvironmentVT?

**Comment by uwecl** [comment]
Zur Sache mit dem Namen einer Rolle: Steht so nicht explizit im Text, oder? Zur Unterscheidung ergibt es denke ich schon Sinn. Das wurde meiner Meinung nach ja auch beim letzten Treffen in einer anderen Gruppe so diskutiert.

Wegen den Assembly Connectors: Schau mal in den [Branch `projectRestructuring`](https://github.com/uwecl/MDSD-Praktikum/tree/projectRestructuring). Da hab ich das rausgenommen, weil wir mit Erik ja besprochen hatten, dass die view types und view points wohl nicht Bestandteil des Modells sind.

**Comment by daseit** [comment]
Genau, Name steht nicht im Text aber irgendwie müssen die ja unterschieden werden. 

Die Frage ist dann nur wie man in den Constraints z.B. auf Links zugreifen kann. 
(Aber sehr schöne Packages! :)

**Comment by uwecl** [comment]
Wie meinst du das mit den Links? Meinst du für die Prüfung von `objA.attribute = objB`?

(Kommentare zur Restrukturierung gerne [hier](https://github.com/uwecl/MDSD-Praktikum/pull/7). ;-) )

**Comment by uwecl** [comment]
Für den Meilenstein geschlossen. Sollte natürlich ständig weiter beachtet und angewandt werden. ;)
