### ISSUE TITLE
ProvidedRoles einer Component

### ISSUE THREAD

**Issue by uwecl** [uwecl/MDSD-Praktikum#31]
Im aktuellen Metamodell kann eine `Component` nur _eine_ `ProvidedRole` haben. Das ist meiner Meinung nach falsch und müsste _min. eine_ sein.

Was meint ihr, @daseit und @uebaa?

**Comment by daseit** [comment]
Deswegen?

> Components have a name and provide interfaceS to other components

**Comment by uwecl** [comment]
Ja, und allein wegen der Logik. ;-)

**Comment by uebaa** [comment]
Mir ist wohl gerade nicht mehr so ganz klar wie sich unser Meta-Modell mit der Zeit entwickelt hat und aus welchen Gründen...weil meiner Meinung nach dürfte eine Komponente keine direkte Verbindung mit `ProvidedRole` haben, sondern dessen `AssemblyContext` der diese Komponente instanziiert.

> Provided and required interfaces of a component result in provided and required roles for the assembly context of the component

Aber auch in dem Falle wie es jetzt modelliert ist, denke ich auch, dass es "mindestens 1" heißen müsste.
