### ISSUE TITLE
Vererbung für Interfaces

### ISSUE THREAD

**Issue by uwecl** [uwecl/MDSD-Praktikum#38]
Interfaces sollen voneinander erben können.

**Comment by daseit** [comment]
Entweder ich hab gerade einen Denkfehler, oder die Beziehung im Metamodel sollte keine Vererbung sondern einfach eine Selbstreferenz sein.  Sonst hat man doch keinen Mehrwert, oder?

**Comment by uwecl** [comment]
Wie wird den die Vererbung im `InheritingInterface` abgebildet? Gar nicht? Dann wäre eine Selbstreferenz wohl zielführender. 

Wobei Erik ja ausdrücklich gesagt hat, es soll als Vererbung realisiert werden.

Wie sich das dann allerdings umsetzen lässt, kann ich dir im Moment nicht sagen.

**Comment by daseit** [comment]
In der MFS Instanz kann ich auf jeden Fall keine Kette erstellen. Immer nur entweder ein InheritingInterface oder ein Interface. Und selbst wenn, es gibt doch immer nur eine Liste mit Signaturen...

**Comment by uwecl** [comment]
Hmm, verstehe. 
Du kannst Erik auch ne Mail schreiben und ihm die Probleme erklären, oder was meinst du?

**Comment by daseit** [comment]
hab ihn gefragt, Selbstreferenz ist richtig.
