### ISSUE TITLE
Constraint SameParentContainerOrLinkedContainerOfconnectedAssemblyContexts

### ISSUE THREAD

**Issue by daseit** [uwecl/MDSD-Praktikum#39]
Wenn durch Links mehrere Container in einer Kette verbunden werden, kann es dann eine Verbindung (z.B verbundene Rollen durch AssemblyConnector) geben, die Container 'überspringt'?

**Comment by uwecl** [comment]
Ich verstehe die Frage glaube ich nicht genau. Was hat die Verbindung eines `AssemblyConnectors` mit den `Links` zwischen `Containern` zu tun?

**Comment by daseit** [comment]
Die AssemblyContexte der durch den `Connector`verbundenen provided - required Rollen müssen entweder im gleichen Container sein, oder die Container müssen über Links verbunden werden. Meine Frage ist ob dann die Links auch zusammengefasst werden (z.B. eine Verbindung zwischen Client<->Application Server <-> Database Server)
Ich hätte gesagt, dass man dann keine Verbindung direkt von Client auf den Database Server bilden kann.

**Comment by uwecl** [comment]
Ah.. Ja, dem würde ich so auch zustimmen. Wobei das bestimmt von der Argumentation abhängt.. ;)

**Comment by daseit** [comment]
Wenn @uebaa nichts dagegen hat schließ ich das hier : )
