### ISSUE TITLE
PCM Invariant: ProvidedRolesMustBeBound

### ISSUE THREAD

**Issue by uebaa** [uwecl/MDSD-Praktikum#40]
Nachdem ich das Problem mit dem Invariant `SystemMustHaveAtLeastOneProvidedRole` gelöst hab, tritt nun bei der Validation des folgenden Invariant ein Fehler auf, der durch die hinzugekommene `ProvidedRole` beim System nun ausgelöst wird:

> **ProvidedRolesMustBeBound:**
> This constraint ensures that all outer provided roles of a system have a provided delegation conector that binds them to something. It does not check whether the binding is correct (inner role not null and matching interfaces)

Bisher treten `DelegationConnector`en nur beim `CompositeComponent` im Repository auf, deshalb ist mir jetzt nicht ganz klar an welcher Stelle dieser fehlende `DelegationConnector` auftauchen soll und was dabei die innerere und äußere `ProvidedRole` sein sollen....

**Comment by uwecl** [comment]
Das ist richtig, das muss in unserem Metamodell noch modelliert werden.

Ein `DelegationConnector` verbindet zwei Rollen vom gleichen Typ (provided oder required). Die äußere `ProvidedRole` wäre damit die, auf die das `ComponentBasedSystem` referenziert. Die innere wäre die Rolle der Komponente im System, welche diese Schnittstelle anbietet.

**Comment by daseit** [comment]
Es geht doch um die ProvidedRole des Systems, oder? Ich dachte wir wollten die gerade nicht durch einen DelegationConnector darstellen. Dafür gibts doch die Referenz?

**Comment by uwecl** [comment]
Achso, ja richtig. Hatten wir so besprochen. Das System ist in diesem Sinne keine `CompositeComponent` sondern bietet die Schnittstelle "direkt" an.

Danke, @daseit! 👍
