### ISSUE TITLE
MFSMerged Modell validieren

### ISSUE THREAD

**Issue by uwecl** [uwecl/MDSD-Praktikum#41]
Das MFSMerged Modell wirft beim validieren momentan noch einige Fehler.

Das sollten wir noch vervollständigen (im Sinne von Aufgabe 1), oder?

**Comment by daseit** [comment]
Sicher, dass du die aktuelle Version vom Master-Branch hast (letzte Änderung war [1..*] providedrole)? Bei mir kommen keine Fehler. Welche constraints sind es denn?

**Comment by uwecl** [comment]
Du hast recht! Ich hatte eine Kopie von dem Projekt im Workspace und keinen Link.. Jetzt ist alles in Ordnung. Danke! 👍
